#!/usr/bin/env bash
# Script qui configure /etc/hosts pour mapper localhost et facebook.com

tmpfile=$(mktemp)

sed 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts > "$tmpfile"
echo "8.8.8.8 facebook.com" >> "$tmpfile"

sudo cp "$tmpfile" /etc/hosts
rm "$tmpfile"
