#!/usr/bin/env bash
# Script qui modifie /etc/hosts pour changer les IP de localhost et facebook.com

# Ajouter les nouvelles règles en fin de fichier
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
