#!/usr/bin/env bash
# Script qui configure /etc/hosts pour mapper localhost et facebook.com

sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
